blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<int:post_id>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:post_id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:comment_id>/remove/', views.comment_remove, name='comment_remove'),
    path('comment/<int:comment_id>/approve/', views.comment_approve, name='comment_approve'),
    path('signup/', views.signup, name='signup'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    # path('accounts/login/', auth_views.LoginView, name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout', kwargs={'next_page': '/'}),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)



    def publish(self):
        self.published_date = timezone.now()
        self.save()

    # creating method for approved comments only to display for home page.we say this function a method because its the part of a class.
    def approved_comments(self):
        return self.comments.filter(approved=True)
    # create a string representation,rather then object form.good practice too.
    def __str__(self):
        # return f"({self.title} by {self.author})"
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments') #that related name is used when we want to access our all comments of a specific post.
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()


    def __str__(self):
        return self.text
    

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('Sign up', 'Sign up', css_class='btn btn-primary'))
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Post, Comment
from .forms import PostForm, CommentForm, UserForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.
def post_list(request):
    # posts = Post.objects.filter(published_date__lte=timezone.now())
    # posts = Post.objects.all().order_by('-published_date')
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    stuff_for_frontend = {'posts': posts}
    return render(request, 'blog/post_list.html', stuff_for_frontend)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    stuff_for_frontend = {'post': post}
    # return render(request, 'blog/post_detail.html', {'post': post})
    return render(request, 'blog/post_detail.html', stuff_for_frontend)
@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', post.id)
    else:
        form = PostForm()
        stuff_for_frontend = {'form': form}
    return render(request, 'blog/post_edit.html', stuff_for_frontend)
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save() # we cannot write the commit = True if we want so,because by default save() method have commit = True.
            return redirect('blog:post_detail', post.id)

    else:
        form = PostForm(instance=post)
        stuff_for_frontend = {'form': form, 'post': post}
    return render(request, 'blog/post_edit.html', stuff_for_frontend)
@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by("-created_date")
    stuff_for_frontend = {'posts': posts}
    return render(request, 'blog/post_draft_list.html', stuff_for_frontend)
@login_required
def post_publish(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.publish()
    return redirect('blog:post_detail', post.id)

@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    # return redirect('blog:post_list', post.id) cannot redirect it to url blog:post_list because after deleting the post program again going to find primary_key post.id of that post which is not exist in program after deleting the post so we use a backslash here because it don't check for primary key in return
    return redirect('/', post.id)

@login_required
def add_comment_to_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', post.id)

    else:
        form = CommentForm()
        stuff_for_frontend = {'form': form}
        return render(request, 'blog/add_comment_to_post.html', stuff_for_frontend)
@login_required
def comment_remove(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id) 
    comment.delete()
    # return redirect('blog:post_detail', comment.post.id)
    return redirect('blog:post_detail', comment.post.id)

@login_required
def comment_approve(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.approve()
    return redirect('blog:post_detail', comment.post.id) #as we know this is reverse view function after something happening on front and so here we cannot return the reverse function by passing comment i.d,we have to return the post i.d to i.t after removing comment from front end,which exactly we do here.


# register

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('/')
        
    else:
        form = UserForm()
    return render(request, 'blog/signup.html', {'form': form})

blog/templates/blog/add_comment_to_post.html
{% extends "base.html" %}
{% block title %}Adding a comment{% endblock  %}
{% block content %}
    <form class="post-form-blog" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">post</button>
    </form>
{% endblock  %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load markdownify %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="post">

        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>

        {% else %}
            <a href="{% url 'blog:post_publish' post.id %}" class="btn btn-primary">Publish</a>

        {% endif %}

        {% if user.is_authenticated and request.user == post.author %}
            <a href="{% url 'blog:post_edit' post.id %}"><i class="fas fa-edit fa-2x" style="color: #339af0"></i></a>
            <a href="{% url 'blog:post_delete' post.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this post?')"><i class="fas fa-eraser fa-2x"></i>
            </a>
        {% endif %}


        <h1>{{ post.title }}</h1>
        <p>{{ post.text | markdown | safe }}</p>
    </div>

    <hr>
    <a href="{% url 'blog:add_comment_to_post' post.id %}" class="btn btn-secondary">Add comment</a>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved %}
            <div class="comment">

                <div class="date">
                    {{ comment.created_date }}
                </div>

                {% if not comment.approved and user.is_superuser %}

                    <a href="{% url 'blog:comment_approve' comment.id %}"><i class="fas fa-check"></i>approve</a>

                    <a href="{% url 'blog:comment_remove' comment.id %}"><i class="fas fa-trash-alt">delete</i></a>
                    <!-- here in below elif tag we say that if comment.author is authenticated user or is a super user then show the following -->
                {% elif comment.author == request.user.username and user.is_authenticated %}
                    <a href="{% url 'blog:comment_remove' comment.id %}"><i class="fas fa-trash-alt">delete</i></a>
                    <a href="{% url 'blog:comment_approve' comment.id %}"><i class="fas fa-check"></i>approve</a>
                {% endif %}
                <br>
                <strong>user: {{ comment.author }}</strong>
                <p>{{ comment.text | markdown | safe | linebreaksbr }}</p>
            </div>

        {% endif %}
    {% empty %}
        <p>No comments yet...</p>

    {% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends "base.html" %}
{% block title %}my drafts{% endblock  %}
{% block content %}
  {% for post in posts %}
    <div class="post">
      <p class="date">created: {{ post.date_created|date:'d-m-Y' }}</p>
      <h1><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>/h1>
      <p>{{ post.text|truncatechars:50}}</p>
    </div>
    {{ post }}
  {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends "base.html" %}
{% block title %}{{post.title}}{% endblock %}
{% block content %}
  <h1>new post</h1>
    <form method="post" class="post-form-blog">
      {% csrf_token %}
      {{ form.as_p }}
    <button type="submit" class="btn btn-primary">save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% load markdownify %}
{% block title %}my blog{% endblock %}
{% block content %}
{% for post in posts %}
<div class="post">

    <div class="date">
        <p>Published: {{ post.published_date }}</p>
    </div>

    <h1>
        <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
    </h1>
    <!-- <p>{{ post.text|linebreaksbr }}</p> -->
    <p>{{ post.text | markdown | safe | truncatechars:600 | linebreaksbr }}</p>

    <!-- showing approved comments at home page "post_list" -->
    <a href="{% url 'blog:post_detail' post.id %}">Comments: {{ post.approved_comments.count }}</a>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog/signup.html
{% extends "base.html" %}
{% block title %}SignUp{% endblock  %}
{% load crispy_forms_tags %} 

{% block content %}
    <div class="panel panel-default" style="width: 400px; margin: 0 auto;">
        <h3 style="text-align: center; font-family: sans-serif;">SignUp for your today.</h3>
        <div class="panel-body">
            {% csrf_token %}
            {% crispy form %}
        </div>
    </div>
{% endblock  %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock  %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata&display=swap" rel="stylesheet" type="text/css" />
    <!-- our base css file below -->
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <!-- below fontawesome link -->
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'zenburn.css' %}">
    <!-- source code pro link below -->
    <link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@500&display=swap" rel="stylesheet">
</head>

<body>
    <div class="page-header">
        {% if user.is_authenticated %}          
        <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><i class="fab fa-firstdraft fa-2x"></i></a>
        <a href="{% url 'blog:post_new' %}" class="top-menu"><i class="fas fa-plus fa-2x"></i></a>
        <p class="top-menu">{{ user.username }} <small><a style="color: white;" href="{% url 'logout' %}">(log out)</a></small></p>
        {% else %}
        <a href="{% url 'login' %}" class="top-menu"><i class="fas fa-sign-in-alt fa-2x"></i></a>
        {% endif %}
        <h1><a href="{% url 'blog:post_list' %}">my blog</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>